### ISSUE TITLE
http 模式下 添加与机器人交互 是怎么实现的

### ISSUE THREAD

**Issue by ELLIEbleu** [bearyinnovative/hubot-bearychat#13]

**Comment by bcho** [comment]
Hi, 使用 http 模式需要把 hubot 运行在服务器上，然后把 hubot 监听的地址填写到 BearyChat 上 hubot 的 `Hubot URL` 内。这样就可以在 hubot 中收到对应的交互消息了。

**Comment by ELLIEbleu** [comment]
@bcho  在启动 ./bin/hubot -a bearychat 之前设置环境变量  export HUBOT_BEARYCHAT_MODE=rtm
就是想文献rtm 和http模式的区别

**Comment by bcho** [comment]
@ELLIEbleu 

http 模式就是使用了 hubot 内置的 http 功能，启动了一个 HTTP 服务。然后 BearyChat 这边在设置正确后，会把相关消息推送到这个 hubot 的 HTTP 监听端口上。启动方式为：

```
export HUBOT_BEARYCHAT_MODE=http
./bin/hubot -a bearychat
```

http 模式下，hubot 只能被动接收 BearyChat 发过来的消息并作出响应。

rtm 模式则是通过 websocket 协议，直接连接到 BearyChat 这边，获取实时的消息，启动方式为：

```
export HUBOT_BEARYCHAT_MODE=rtm
./bin/hubot -a bearychat
```

rtm 模式下，hubot 能够实时收到 BearyChat 发过来的消息、事件并作出响应。

**Comment by ELLIEbleu** [comment]
@bcho  想问下 bearychat 下用户发送消息后  hubot接收到的message.user.name 转码了，不是原来的，你知道怎么得到原来真实name的吗

**Comment by bcho** [comment]
这个名字应该不会被转码。message.user.name 应该就是发送消息的用户的用户名（不是显示昵称，用户名形式为类似 `@hbc` 的形式，发送过来的数据没有 `@`）。请问是在什么模式下会出现你说的情况？另外能提供一下具体的数据日志吗？

**Comment by ELLIEbleu** [comment]
@bcho 已经解决了 message.user.name 获得不是用户真实的name ,你可以
console.log  "#{message.user.name}"  查看下

**Comment by bcho** [comment]
对，这里要区分一下，用户名是 `message.user.name` 但是 BearyChat 界面里面显示的名字不一定是用户名（可以在团队设置中选择优先显示全名还是用户名）

**Comment by albertshao** [comment]
@ELLIEbleu 请问一下你是如何解决的，在hubot中获取bearychat里面显示的用户名？

**Comment by ELLIEbleu** [comment]
@albertshao 
![image](https://user-images.githubusercontent.com/13954035/41755009-b5add24e-7607-11e8-92b5-ee3a19b4e7be.png) 你可以设置下子
