### ISSUE TITLE
实现自动重连

### ISSUE THREAD

**Issue by bcho** [bearyinnovative/hubot-bearychat#18]

**Comment by loddit** [comment]
![image](https://cloud.githubusercontent.com/assets/394562/25896321/54634240-35b6-11e7-96fb-d90a3dbcbcb1.png)
基本实现思路。
如何更及时的判断断线没有在这里图里体现，暂时先用 ws 对象自己的 close 事件。

**Comment by bcho** [comment]
基本 LGTM
