### ISSUE TITLE
在 rtm 模式下能否支持 robot.messageRoom 方法

### ISSUE THREAD

**Issue by wutz** [bearyinnovative/hubot-bearychat#21]
我尝试在 `rtm_client.coffee` 的 `packMessage` 方法的最后一行前增加:

```
if envelope.room
  message = { channel_id: envelope.room }
  return rtm.message.refer message, text
```

可以正常工作

**Comment by qiibinn** [comment]
我加上后还是没法往room里发消息。

**Comment by wutz** [comment]
`robot.messageRoom` 这个方法还没有实现，我临时使用的方法是：
```
robot.router.post '/hooks', (req, res) ->
    robot.emit 'bearychat.attachment', 
        message: { room: { vchannelld: '<your_vchannel_id>' } }
        text: 'test'
```

其中 `<your_vchannel_id>` 的获取方法：

```
robot.hear /vchannel/i, (res) ->
    res.reply res.message.user.message.vchannel_id
```

在 `BearyChat` 中 `@hubot vchannel` 即可获得

> 关键点要拼出 ` message: { room: { vchannelld: '<your_vchannel_id>' } }`

**Comment by qiibinn** [comment]
![image](https://cloud.githubusercontent.com/assets/16411302/26433767/300f528a-4137-11e7-86f1-e196704092ed.png)
已经搞定了，多谢。
