### ISSUE TITLE
定义两个attachment会混淆

### ISSUE THREAD

**Issue by qiibinn** [bearyinnovative/hubot-bearychat#30]
```
robot.respond '念两句诗', (res) ->
  robot.emit 'bearychat.attachment',
    # required
    message: res.message
    # requried
    text: '当时我就念了...'
    attachments: [
      {
        color: '#cb3f20',
        text: '苟利国家生死以',
      },
      {
        text: '岂因祸福避趋之',
      },
      {
        images: [
          {url: 'http://example.com/excited.jpg'},
        ]
      }
    ]

robot.respond '念句诗', (res) ->
  robot.emit 'bearychat.attachment',
    # required
    message: res.message
    # requried
    text: '当时我就念了...'
    attachments: [
      {
        text: '岂因祸福避趋之',
      },
      {
        images: [
          {url: 'http://example.com/excited.jpg'},
        ]
      }
    ]
```

**Comment by loddit** [comment]
可以使用 ``` 的 markdown 标记发多行代码，避免格式丢失。

**Comment by qiibinn** [comment]
我的意思说说我 @hubot 念两句诗，   返回的是 “念两句诗” 和“念句诗”  两个命令的结果， 而我只想要一个的

**Comment by qiibinn** [comment]
robot.respond '念两句诗', (res) ->
robot.respond '念句诗', (res) ->

**Comment by loddit** [comment]
`rebot.respond` 的第一参数应该是一个正则表达式，比如 `/念两句诗/` ，如果是字符串不论你说什么的话都会匹配。 详细请看 https://github.com/github/hubot/blob/master/docs/scripting.md

**Comment by qiibinn** [comment]
确实如此！多谢了。 

还有个问题， 我想 访问一个url， 把url的内容返回， 但是返回的是字符串格式，html的标签都显示了。
 为啥不能是HTML的样式？

**Comment by qiibinn** [comment]
robot.respond /调用链接/i, (msg) ->
    robot.http('http://www.google.com/')
      .get() (err, res, body) ->
        msg.send body
返回的是字符串，不是一个网页的样子。

**Comment by loddit** [comment]
我把这个 issue 关了。
因为直接可以嵌入 HTML 从安全性来说是很难保证的，所以我们不会支持外部来源 HTML 直接渲染。
另外如果是抓取网页内容的需求，比较合理的解决方式是：机器人也只需要发出链接的 URL，BearyChat 会自动抓取页面摘要，而不是你把网页内容都通过机器人返回。现在我们对抓取的策略还在完善中， zhihu douban stackoverflow v2ex 等等很多网站是支持抓取的。

**Comment by qiibinn** [comment]
好的。 
我们需要支持html渲染，是因为也许网页内容是从内网地址获取的。  如果通过bearychat去抓取，没法抓取内网内容。 所以这个提供这个功能对我们很关键。也是我们做这个聊天机器人的主要目的。
安全很大部分和管理有关， 作为一个面向企业的工具软件，提供全面的功能更重要。

**Comment by loddit** [comment]
如果是内网的内容，建议你们不直接抓取全部 HTML，使用  [jquery](https://www.npmjs.com/package/jquery) 或者 [cheerio](https://www.npmjs.com/package/cheerio) 等带有 HTML 解析器的库，提取出需要的部分。
当然如果可能，最好的方式是内网的服务提供 API ，可以由 Hubot 直接调用，避免抓取的种种问题。

**Comment by qiibinn** [comment]
好的，多谢！
