### ISSUE TITLE
机器人发送attachments显示错误，显示为[object Object]

### ISSUE THREAD

**Issue by dongorigin** [bearyinnovative/hubot-bearychat#43]
直接复制官方示例 https://github.com/bearyinnovative/hubot-bearychat/blob/master/scripts/attachments_example.coffee  
发送后text正常，attachments部分显示为[object Object]
<img width="281" alt="screen shot 2017-10-29 at 17 04 18" src="https://user-images.githubusercontent.com/6520963/32142094-4a5e9a96-bccb-11e7-9a9c-78c8dd12ce0e.png">

**Comment by shonenada** [comment]
Hi ，可以看看代码吗？下面是我使用 example 的代码进行测试的结果：

![image](https://user-images.githubusercontent.com/2056489/32156883-eee0d880-bd0d-11e7-8349-e48c84424a60.png)

如果方便的话，欢迎加入 [feedback@bearychat](https://feedback.bearychat.com/apply) 沟通。

**Comment by dongorigin** [comment]
https://github.com/bearyinnovative/hubot-bearychat/blob/master/scripts/attachments_example.coffee
就是这里的代码，直接使用，分毫未动


完整代码在这里，我测试的时候真的是完全覆盖的官方示例，依然无效
https://github.com/dongorigin/hubot-sample

**Comment by shonenada** [comment]
Hi @dongorigin ~ 的确是有问题，我们现在处理，处理完通知一下你~

**Comment by shonenada** [comment]
@dongorigin 你好，example 已经更新了，你可以尝试更新。 
https://github.com/bearyinnovative/hubot-bearychat/blob/master/scripts/attachments_example.coffee 。

**Comment by dongorigin** [comment]
好的，没问题了
