### ISSUE TITLE
安全问题

### ISSUE THREAD

**Issue by zyf0330** [bearyinnovative/hubot-bearychat#8]
使用 `rtm` 模式时，安全问题值得考虑吗？

**Comment by bcho** [comment]
rtm 模式和在 web 上登录 `{subdomain}.bearychat.com` 进行聊天效果一致（都是通过 websocket 连接到聊天服务）。目前通过 rtm token 来进行授权认证。请问有哪些安全问题是需要额外考虑的？

**Comment by zyf0330** [comment]
rtm 模式是使用 websocket 吗？但是服务器没有证书，所以不能使用 wss 吧？

**Comment by bcho** [comment]
> rtm 模式是使用 websocket 吗？

是使用 websocket

> 但是服务器没有证书，所以不能使用 wss 吧？

rtm 模式下，websocket 服务器是 bearychat. hubot-bearychat 会作为 websocket client 端接入。
现在 rtm 模式使用的 websocket 协议也是 wss.

**Comment by zyf0330** [comment]
我知道了。原来 hubot 是客户端。那么我填写的 **hubot url** 有什么用呢？不是用于 rtm 模式的吗？

**Comment by zyf0330** [comment]
只是用来请求

**Comment by bcho** [comment]
> 那么我填写的 hubot url 有什么用呢？不是用于 rtm 模式的吗？

如果使用 rtm 模式就不需要填写了（hubot url 是给 http 模式使用的，http 模式中 hubot-bearychat 作为 server 端），更新后的 hubot 设置文档会在近日上线。

**Comment by zyf0330** [comment]
ok！
